# -*- coding: utf-8 -*-
"""Fashion MNIST Mini Project With CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P5gsi5b1TrCMcr-EU-agTYEHvrfTjcsb
"""

import tensorflow as tf 
mnist = tf.keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3, 3), activation='relu',
            input_shape=(28, 28, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  # tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
  # tf.keras.layers.MaxPooling2D(2,2),
  
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'), 
  tf.keras.layers.Dense(64),
])

predictions = model(x_train[:20]).numpy()
tf.nn.softmax(predictions).numpy()

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:20], predictions).numpy()

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10)

model.evaluate(x_test,  y_test, verbose=2)